function  mkgraph(x,y,pl)

plot(x,y,pl,...
                'LineWidth',2,...
                'MarkerEdgeColor','k',...
                'MarkerFaceColor',[.49 1 .63],...
                'MarkerSize',25);
end

